# Docker Compose File (docker-compose.yml)
version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: employee_register_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: EmployeeRegisterDb
      MYSQL_USER: employee_user
      MYSQL_PASSWORD: employee_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
